// One-off: converts the original JPEGs into web-sized WebP + a photo manifest.
// Usage: node scripts/process-photos.mjs [sourceDir]
import sharp from 'sharp'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'

const SOURCE = process.argv[2] ?? path.join(os.homedir(), 'Downloads')
const OUT_DIR = path.join('src', 'assets', 'photos')
const MANIFEST = path.join('src', 'photos.js')
const LONG_EDGE = 1600

// The 15 photos for the page, in the order they should appear.
const ORIGINALS = [
  'IMG_0590.jpeg', 'IMG_0703.jpeg', 'IMG_0839.jpeg', 'IMG_1409.jpeg',
  'IMG_1467.JPG', 'IMG_1764.jpeg', 'IMG_1841.jpeg', 'IMG_1868.jpeg',
  'IMG_1869.jpeg', 'IMG_2003.jpeg', 'IMG_3548.jpeg', 'IMG_3903.jpeg',
  'IMG_7566.jpeg', 'IMG_7638.jpeg', 'IMG_8817.jpeg',
]

await fs.mkdir(OUT_DIR, { recursive: true })

const entries = []

for (const [i, original] of ORIGINALS.entries()) {
  const id = `p${String(i + 1).padStart(2, '0')}`
  const input = path.join(SOURCE, original)
  const pipeline = sharp(input).rotate() // bake in EXIF orientation

  // Dimensions must come from the resized output: EXIF-rotated originals
  // report their pre-rotation width/height in metadata.
  const { width: w, height: h } = await pipeline
    .clone()
    .resize({ width: LONG_EDGE, height: LONG_EDGE, fit: 'inside', withoutEnlargement: true })
    .webp({ quality: 80 })
    .toFile(path.join(OUT_DIR, `${id}.webp`))

  // Tiny blurred stand-in so photos fade in from a shape, not from nothing.
  const lqip = await pipeline
    .clone()
    .resize({ width: 20, fit: 'inside' })
    .blur(1.5)
    .webp({ quality: 45 })
    .toBuffer()

  entries.push({ id, w, h, lqip: `data:image/webp;base64,${lqip.toString('base64')}`, original })
  console.log(`${original} -> ${id}.webp  ${w}x${h}`)
}

const manifest = `// GENERATED by scripts/process-photos.mjs -- do not edit by hand.
${entries.map((e) => `import ${e.id} from './assets/photos/${e.id}.webp'`).join('\n')}

export const photos = [
${entries
  .map((e) => `  { id: '${e.id}', src: ${e.id}, w: ${e.w}, h: ${e.h}, lqip: '${e.lqip}' },`)
  .join('\n')}
]

export const byId = Object.fromEntries(photos.map((p) => [p.id, p]))
`

await fs.writeFile(MANIFEST, manifest)
console.log(`\nWrote ${MANIFEST} (${entries.length} photos)`)
