// GENERATED by scripts/process-photos.mjs -- do not edit by hand.
import p01 from './assets/photos/p01.webp'
import p02 from './assets/photos/p02.webp'
import p03 from './assets/photos/p03.webp'
import p04 from './assets/photos/p04.webp'
import p05 from './assets/photos/p05.webp'
import p06 from './assets/photos/p06.webp'
import p07 from './assets/photos/p07.webp'
import p08 from './assets/photos/p08.webp'
import p09 from './assets/photos/p09.webp'
import p10 from './assets/photos/p10.webp'
import p11 from './assets/photos/p11.webp'
import p12 from './assets/photos/p12.webp'
import p13 from './assets/photos/p13.webp'
import p14 from './assets/photos/p14.webp'
import p15 from './assets/photos/p15.webp'

export const photos = [
  { id: 'p01', src: p01, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBQCdASoUABsAPt1gqEyopaQiMAgBEBuJQBajbIBMEg3E9cGYN49eUPULixejpYrfHgAA/slQt5e1irktfG3Hd6Z875TcYRVMRnvaCN0TJH6k+13wL/m/v4jcCWvwXBMJsLDrWK9oCn9rAInDVslav+Qt+B4mfoHUk8TOcqJlZKiIAAAAAA==' },
  { id: 'p02', src: p02, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBQCdASoUABsAPt1cqU8opKOiMBgIARAbiWQAnTKEfOgz3+FMTq/xqJTCR4pBlh+jyZEAAP4VzkB2Ifgjc9UOKXGDS4d7wwf8iibF69YM60m9X7RYwYSxCtGLL8URYrAf852n7RkAi1N1IL77CyJo2+al3L9bWvUcN744L3pfQaWVImXVKEp+H2jeY0bT+HLyvAAA' },
  { id: 'p03', src: p03, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBQCdASoUABsAPsVQoEynpKMiN+gA8BiJZACdMySwtFlcPFdx0W9UoZK1MndzNTla8cwAAPyK83fY+injLdOi/sbLRIoesjcjuvN7aVp18VvGMrT7l3LujjQblwZyHuYAowsqZ6XM9NaLgvWAhgAPcR+CN/LfNfcNMpLe5VF24PAAAAA=' },
  { id: 'p04', src: p04, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBQCdASoUABsAPt1ipk6opaMiKA1REBuJQBlACLrwFcpARV6l62t6uy4tm8pttcAAAP7xxbCThCzQ4RKke7nZLrnxk9kmkJd3inD4NlDaCU25B7Pshy1x959Bmzw5NHDzNgf/u7PdUojeVeVEd8HonScnOmnu+BN/LkwAAAA=' },
  { id: 'p05', src: p05, w: 480, h: 640, lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBQCdASoUABsAPt1kqk+opaOiKAqpEBuJYgCdMuN+J3+BrTj+pj+zRHLeqHQ3o+N6RZNoAPgD9SjAwTfURmJsBaVICEf+Et7I7mCos5NPaXG4FYkTFSOXLqCyDJuWjs29bIGMVG/OpnLbESGbJwSOJz1QRENa/NUNl5C+ulK59QaPf3MUq1UBHgAAAA==' },
  { id: 'p06', src: p06, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBQCdASoUABsAPt1ep0yopSOiMAgBEBuJZgCdMt8C27YWUkdJYq2aR+YNMqIX/I4IAAD470fr8tMm8HGStDrZP+ujMtxGNW/qzkZQ6+GjLfyK51QBsxkFzabMYmGJF3ZTkgT6NQjBxMOsypmYTeDf6K68Y28Y0ZhcJago5r1z8/6EDkYNGhEBqAA=' },
  { id: 'p07', src: p07, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACQBQCdASoUABsAPtlWpUyoJKOiN/VYAQAbCUAYAZ/gw1bmFXj0MzDoRbR99IzXyspPQtGuAAD8Gty39lS3lbD5KsyzVFel1qR02z52h86PTNcFBkkCXDr74+DsN/aoKB3wsXF9qtNNyIp91WoxsRnq6iFkB6F2SaCHh5QxREA5WVFHKE5cjC9ApNXEdhngAAA=' },
  { id: 'p08', src: p08, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQBQCdASoUABsAPt1gpk0opaOiMAgBEBuJYwCxDV69VtAAEtxSICXRvMNkmQhha7MFc/ZGIAoAAP5S/W3PGLddYivnRsZqwrCeX4Kj0hHuN7FUawU7OC0kYz1oaRuUqzft2/SEb9JkxlvD6qO2kWjSYZuJavMgFe6ogg8po6Tq4AAA' },
  { id: 'p09', src: p09, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwBACdASoUABsAPt1gqE4opaOiKA1REBuJZQDImAvZpBM7ma3dE2RnOc4uoAD6+eYIKQW+L94Zp5KaPLcl34knfde187MksgbEh7KMdIOwdgN8+dY2AP1ZA6rkc0bNgfPVuKt1uxTDgAAA' },
  { id: 'p10', src: p10, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBQCdASoUABsAPsVQoEynpKMiN+gA8BiJYwC2+47EZYw06+F9hiRp6YQRSOXs05dQAPOHYYzR8/WhDqBrDSWeKQjXoQNo1NC37o906538FepIPC0hx2RyixYEuKrHl4TALsHpfpkIu/RQAAA=' },
  { id: 'p11', src: p11, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABwBQCdASoUABsAPt1gpkyopiOiMBgMARAbiUATploQGwE3F8dkjJ2TO556zBzK2+S4k3/QAPnob4ID05iuEtnbNOeKX9KKz26XkAvZEMXtPvpZgYPqBMYCrOH1l9k1ONqhddcklhRuyDji2LgQ8CYgYqkbr6WU8EekphmgPzJz2E4ufOQjdcAA' },
  { id: 'p12', src: p12, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADQBACdASoUABsAPt1cqU6opKOiMBgIARAbiWYAtRfCQHY0xpqOQ3kkF702wO7WQADeZSzFVjBP5tPUdf1xFHPtdb0AXxQUQ3dZwDhRu1EdLX6aCaekhxh4tr/rbH8UUk68g00qG+Fzh15Mqe3QbDWmgtjkmZzUzgAJPVB4RjRFJ1WQ/PyzdbDnuUAitJvAAAA=' },
  { id: 'p13', src: p13, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACwBQCdASoUABsAPt1gqE4opaOiMBgIARAbiUAX7Vvgnc7Itp+ZSuXDTy6O84yxolNoXwkDgcAA/FyCd5w+0L8sKJGqpLlWvtaATL1CjKgddM+77Ckdp9vbDb/7z4+HwlLq0KLibSrnQy5OsddY5n179HNKeF1gsWdaRbCOYgXOkkLyyUUQV4j+zQAAAA==' },
  { id: 'p14', src: p14, w: 1600, h: 1200, lqip: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoUAA8APt1cp0yopSOiMAgBEBuJZACdLwABor9ath+Ji2ChAAD+zeXJAvNi9AgHJK8Et3e0JVVxPToptOiuzQ+j4kiS89S5yrATEa2sHmKICWFHZUptAyAA' },
  { id: 'p15', src: p15, w: 1200, h: 1600, lqip: 'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBQCdASoUABsAPt1gqEyopiQiMAgBEBuJQBYj3RBV/TBa+WPd/lJTqvp0j5/942AEAADAf4QgWm3ZTiQi6OJTxTtVZuuqwzFT9yeNf9lHg8LQKUypNjKG7p2xeIoqEXh0zC1vK67pR1CjDSWlfwAA' },
]

export const byId = Object.fromEntries(photos.map((p) => [p.id, p]))
